// GENERATED by crates/core/tests/generated_ts.rs from the Rust core. Do not edit by hand.
// Regenerate with: ATLANTIS_UPDATE_GENERATED=1 cargo test -p atlantis-hud-core --test generated_ts

/** Advisory order-check codes: `codes::ALL` in crates/core/src/orders/semantics.rs, in that order. */
export const ADVISORY_CHECK_CODES = [
  "not-enough-silver",
  "not-enough-items",
  "guard-dropped",
  "hex-unguarded",
  "taught-not-here",
  "taught-not-studying",
  "teacher-cannot-teach",
  "teaching-oversubscribed",
  "teacher-has-free-slots",
  "form-alias-reused",
  "fleet-overloaded",
  "fleet-undercrewed",
  "give-target-not-here"
] as const;

export type AdvisoryCheckCode = (typeof ADVISORY_CHECK_CODES)[number];

/** The order words that move a unit: `MOVEMENT_ORDER_COMMANDS` in crates/core/src/movement/orders.rs. */
export const MOVEMENT_ORDER_COMMANDS = [
  "MOVE",
  "ADVANCE",
  "SAIL"
] as const;

export type MovementOrderCommand = (typeof MOVEMENT_ORDER_COMMANDS)[number];
