[package]
name = "atlantis-hud-desktop-shell"
version = "0.1.0"
edition = "2021"

[features]
default = []
desktop-runtime = []

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
atlantis-hud-core-tauri = { path = "../../../crates/core-tauri" }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
tauri = { version = "2", default-features = false, features = [] }

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
tauri = { version = "2", default-features = false, features = [] }
