//! The TypeScript vocabulary `@atlantis/core-client` re-exports is generated from the core's own
//! constants, here, and this test fails whenever the committed file no longer matches them.

use std::path::PathBuf;

use atlantis_hud_core::movement::orders::MOVEMENT_ORDER_COMMANDS;
use atlantis_hud_core::orders::semantics::codes;

const RELATIVE_PATH: &str = "../../packages/core-client/src/coreVocabulary.generated.ts";
const REGENERATE: &str =
    "ATLANTIS_UPDATE_GENERATED=1 cargo test -p atlantis-hud-core --test generated_ts";

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "// GENERATED by crates/core/tests/generated_ts.rs from the Rust core. Do not edit by hand.\n",
    );
    out.push_str(&format!("// Regenerate with: {REGENERATE}\n\n"));

    out.push_str(
        "/** Advisory order-check codes: `codes::ALL` in crates/core/src/orders/semantics.rs, in that order. */\n",
    );
    out.push_str("export const ADVISORY_CHECK_CODES = [\n");
    let codes: Vec<&str> = codes::ALL.iter().map(|code| code.as_str()).collect();
    for (index, code) in codes.iter().enumerate() {
        let comma = if index + 1 == codes.len() { "" } else { "," };
        out.push_str(&format!("  \"{code}\"{comma}\n"));
    }
    out.push_str("] as const;\n\n");
    out.push_str("export type AdvisoryCheckCode = (typeof ADVISORY_CHECK_CODES)[number];\n\n");

    out.push_str(
        "/** The order words that move a unit: `MOVEMENT_ORDER_COMMANDS` in crates/core/src/movement/orders.rs. */\n",
    );
    out.push_str("export const MOVEMENT_ORDER_COMMANDS = [\n");
    for (index, command) in MOVEMENT_ORDER_COMMANDS.iter().enumerate() {
        let comma = if index + 1 == MOVEMENT_ORDER_COMMANDS.len() {
            ""
        } else {
            ","
        };
        out.push_str(&format!("  \"{command}\"{comma}\n"));
    }
    out.push_str("] as const;\n\n");
    out.push_str("export type MovementOrderCommand = (typeof MOVEMENT_ORDER_COMMANDS)[number];\n");

    out
}

#[test]
fn core_client_vocabulary_matches_the_core() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(RELATIVE_PATH);
    let expected = render();
    if std::env::var_os("ATLANTIS_UPDATE_GENERATED").is_some() {
        std::fs::write(&path, &expected).expect("writes the generated vocabulary");
        return;
    }
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        actual, expected,
        "packages/core-client/src/coreVocabulary.generated.ts is stale; regenerate it with:\n  {REGENERATE}"
    );
}
