//! The TypeScript files `@atlantis/core-client` generates from the Rust core live here: the
//! vocabulary it re-exports from the core's own constants, and the table of parsed structure kinds
//! its `aStructure` fixture builder reads. Each test fails whenever its committed file no longer
//! matches what the core produces.

use std::path::PathBuf;

use atlantis_hud_core::movement::orders::MOVEMENT_ORDER_COMMANDS;
use atlantis_hud_core::orders::semantics::codes;
use atlantis_hud_core::report::region::parse_structure;

const RELATIVE_PATH: &str = "../../packages/core-client/src/coreVocabulary.generated.ts";
const STRUCTURE_KINDS_PATH: &str = "../../packages/core-client/src/structureKinds.generated.ts";
const REGENERATE: &str =
    "ATLANTIS_UPDATE_GENERATED=1 cargo test -p atlantis-hud-core --test generated_ts";

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "// GENERATED by crates/core/tests/generated_ts.rs from the Rust core. Do not edit by hand.\n",
    );
    out.push_str(&format!("// Regenerate with: {REGENERATE}\n\n"));

    out.push_str(
        "/** Advisory order-check codes: `codes::ALL` in crates/core/src/orders/semantics.rs, in that order. */\n",
    );
    out.push_str("export const ADVISORY_CHECK_CODES = [\n");
    let codes: Vec<&str> = codes::ALL.iter().map(|code| code.as_str()).collect();
    for (index, code) in codes.iter().enumerate() {
        let comma = if index + 1 == codes.len() { "" } else { "," };
        out.push_str(&format!("  \"{code}\"{comma}\n"));
    }
    out.push_str("] as const;\n\n");
    out.push_str("export type AdvisoryCheckCode = (typeof ADVISORY_CHECK_CODES)[number];\n\n");

    out.push_str(
        "/** Codes that mark a unit's Silver figure: `codes::SILVER_TROUBLE` in crates/core/src/orders/semantics.rs. */\n",
    );
    out.push_str("export const SILVER_TROUBLE_CODES = [\n");
    let silver: Vec<&str> = codes::SILVER_TROUBLE
        .iter()
        .map(|code| code.as_str())
        .collect();
    for (index, code) in silver.iter().enumerate() {
        let comma = if index + 1 == silver.len() { "" } else { "," };
        out.push_str(&format!("  \"{code}\"{comma}\n"));
    }
    out.push_str("] as const;\n\n");

    out.push_str(
        "/** The order words that move a unit: `MOVEMENT_ORDER_COMMANDS` in crates/core/src/movement/orders.rs. */\n",
    );
    out.push_str("export const MOVEMENT_ORDER_COMMANDS = [\n");
    for (index, command) in MOVEMENT_ORDER_COMMANDS.iter().enumerate() {
        let comma = if index + 1 == MOVEMENT_ORDER_COMMANDS.len() {
            ""
        } else {
            ","
        };
        out.push_str(&format!("  \"{command}\"{comma}\n"));
    }
    out.push_str("] as const;\n\n");
    out.push_str("export type MovementOrderCommand = (typeof MOVEMENT_ORDER_COMMANDS)[number];\n");

    out
}

/// Every structure kind a TypeScript test builds with `aStructure`. The builder takes its split
/// fields from the table generated from this list, so a test that needs a new spelling adds it
/// here and regenerates; nobody re-implements `split_kind` in TypeScript (ah-xi0q).
const FIXTURE_STRUCTURE_KINDS: &[&str] = &[
    "8 Corsairs",
    "Balloon",
    "Bog, closed to player units",
    "Cave",
    "Cloudship, 14 Cloudships, 4 Airships",
    "Cloudship, several Airships",
    "Crypt, closed to player units",
    "Demon Pit, closed to player units",
    "Empowered Altar, closed to player units",
    "Farm",
    "Fleet, 2 Balloons",
    "Fleet, 2 Corsairs",
    "Fleet, 2 Galleons",
    "Fleet, 2 Longships",
    "Fleet, 3 Corsairs",
    "Fleet, 4 Galleons, 1 Balloon",
    "Fleet, 6 Airships",
    "Fleet, 8 Corsairs",
    "Flotilla, 6 Corsairs",
    "Fort",
    "Galleon",
    "Galley",
    "Galley, 2 Dinghies",
    "Galley, 2 Galleys, 3 Galleons",
    "Galley, 40 Galleons",
    "Galley, 40 Galleons, 11 Galleys, 10 Balloons",
    "Gateway, contains an inner location",
    "Giant's Castle, closed to player units",
    "Granary",
    "Hut",
    "Ice Cave, closed to player units",
    "Lair",
    "Lair, closed to player units",
    "Longboat",
    "Longship",
    "Lumberyard",
    "Magician's Tower, closed to player units",
    "Mine",
    "Quarry",
    "Ritual Altar",
    "Road N",
    "Road SW",
    "Ruin",
    "Ruin, closed to player units",
    "Shaft",
    "Shaft, contains an inner location",
    "Stockade",
    "Sunken Palace, closed to player units",
    "Temple",
    "Tower",
    "Whirlpool, closed to player units",
    "road n",
    "road s",
    "road se",
    "road sw",
    "road up",
];

fn render_structure_kinds() -> String {
    let mut out = String::new();
    out.push_str(
        "// GENERATED by crates/core/tests/generated_ts.rs from the Rust core. Do not edit by hand.\n",
    );
    out.push_str(&format!("// Regenerate with: {REGENERATE}\n\n"));
    out.push_str("import type { StructureInfo } from \"./generated/StructureInfo\";\n\n");
    out.push_str(
        "/** The split fields `parse_structure` (crates/core/src/report/region.rs) derives from a kind. */\n",
    );
    out.push_str(
        "export type ParsedStructureKind = Pick<StructureInfo, \"baseKind\" | \"qualifiers\" | \"vessels\">;\n\n",
    );
    out.push_str(
        "/** Every kind in `FIXTURE_STRUCTURE_KINDS` (crates/core/tests/generated_ts.rs), as the parser splits it. */\n",
    );
    out.push_str(
        "export const PARSED_STRUCTURE_KINDS: Readonly<Record<string, ParsedStructureKind>> = {\n",
    );
    for (index, kind) in FIXTURE_STRUCTURE_KINDS.iter().enumerate() {
        let structure = parse_structure(&format!("+ Fixture [1] : {kind}."))
            .unwrap_or_else(|| panic!("parse_structure rejects the fixture kind {kind:?}"));
        assert_eq!(
            structure.kind, *kind,
            "the fixture kind {kind:?} does not survive parse_structure as a kind"
        );
        let entry = serde_json::json!({
            "baseKind": structure.base_kind,
            "qualifiers": structure.qualifiers,
            "vessels": structure.vessels,
        });
        let comma = if index + 1 == FIXTURE_STRUCTURE_KINDS.len() {
            ""
        } else {
            ","
        };
        out.push_str(&format!(
            "  {}: {entry}{comma}\n",
            serde_json::to_string(kind).expect("a kind serialises")
        ));
    }
    out.push_str("};\n");
    out
}

/// Writes `expected` to `relative` under `ATLANTIS_UPDATE_GENERATED`, and otherwise fails when the
/// committed file differs from it.
fn write_or_compare(relative: &str, expected: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative);
    if std::env::var_os("ATLANTIS_UPDATE_GENERATED").is_some() {
        std::fs::write(&path, expected).expect("writes the generated file");
        return;
    }
    // A missing file reads as "stale" (the ordinary case before the first regenerate); any other
    // I/O error - a permissions problem, a wrong relative path - is a real failure and should say
    // so rather than being silently swallowed into an empty-string diff.
    let actual = match std::fs::read_to_string(&path) {
        Ok(contents) => contents,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(error) => panic!("could not read {}: {error}", path.display()),
    };
    let shown = relative.trim_start_matches("../../");
    assert_eq!(
        actual, expected,
        "{shown} is stale; regenerate it with:\n  {REGENERATE}"
    );
}

#[test]
fn core_client_vocabulary_matches_the_core() {
    write_or_compare(RELATIVE_PATH, &render());
}

#[test]
fn structure_kinds_table_matches_the_parser() {
    write_or_compare(STRUCTURE_KINDS_PATH, &render_structure_kinds());
}
