/**
 * Loads the Rust core compiled to WebAssembly.
 *
 * The module is generated by `pnpm --filter @atlantis/web build:wasm` into `src/wasm`, which is
 * gitignored. Vite emits the `.wasm` payload as an asset and the generated glue fetches it
 * relative to itself, so no bundler plugin is needed.
 */

import init, * as core from "./wasm/atlantis_core.js";
import type { CoreWasmModule } from "./webCoreAdapter";

let pending: Promise<CoreWasmModule> | null = null;

/**
 * Instantiates the module once and returns it.
 *
 * Concurrent callers share a single instantiation. A failed load clears the cached promise so a
 * later attempt can retry rather than resolving to a broken module forever.
 */
export function loadCoreWasm(): Promise<CoreWasmModule> {
  if (!pending) {
    pending = init()
      .then(() => core as unknown as CoreWasmModule)
      .catch((error: unknown) => {
        pending = null;
        throw error;
      });
  }

  return pending;
}
